version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile

  blog.signal:
    image: ${DOCKER_REGISTRY-}blogsignal
    build:
      context: .
      dockerfile: src/Blog.Signal/Dockerfile

