version: '3.4'

services:

  postdb:
    container_name: postdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Server=postdb;Database=PostDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - postdb
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  blog.signal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

